-- 009_iso27001_requirement_descriptions.sql
--
-- Carga las descripciones de las clausulas ISO 27001:2022 (MAE_REQUIREMENT.C_DESCRIPTION),
-- clausulas 4 a 10 (Requisitos), extraidas del documento oficial en espanol provisto por el
-- usuario (iso-iec-27001-2022-espanol.pdf). NO incluye el Anexo A (controles), que ya se cargo
-- en 007_iso27001_control_descriptions.sql desde el Excel SoA de ONPE.
--
-- El arbol de MAE_REQUIREMENT mezcla filas "contenedoras" (una clausula/subclausula que solo
-- agrupa a sus hijas, sin texto propio en la norma -- p.ej. "5 Liderazgo" pasa directo a "5.1")
-- con filas "hoja" (el enunciado real de un literal a)/b)/c) o parrafo). Se identifico cada caso
-- recorriendo el arbol completo (N_PARENT_ID) contra el texto oficial antes de escribir este
-- script; las filas contenedoras sin texto propio se dejan vacias a proposito (no es un dato
-- faltante, es que la norma no tiene parrafo en ese nivel -- mismo patron ya verificado en
-- NTP-ISO/IEC 42001, que no necesito ningun script).
--
-- Ademas corrige N_REQUIREMENT_ID_PK=1 ("Contexto de la organizacion", clausula 4 contenedora):
-- tenia una descripcion incorrecta, duplicada por error de carga inicial desde la de la clausula 3
-- ("Terminos y definiciones"). Se limpia a NULL, que es lo que corresponde (clausula 4 tampoco
-- tiene parrafo propio, va directo a 4.1).
--
-- Pendiente conocido (no corresponde a este script): la clausula "6.3 Planificacion de cambios"
-- no existe como fila en MAE_REQUIREMENT (falta en el arbol completo, no es que este vacia).
-- Se necesitaria insertar una fila nueva bajo N_PARENT_ID=8 (Planificacion) para agregarla; no se
-- hizo aqui porque cambia la estructura del arbol, no solo el contenido.
--
-- Probado en DB de desarrollo (Railway). Pendiente de aplicar en produccion.

BEGIN;

-- Corrige la descripcion incorrecta (duplicada de la clausula 3) en la clausula 4 contenedora
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = NULL WHERE "N_REQUIREMENT_ID_PK" = 1;

UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe determinar los problemas externos e internos que sean relevantes para su propósito y que afecten su capacidad para lograr los resultados esperados de su sistema de gestión de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 3;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe determinar los límites y la aplicabilidad del sistema de gestión de la seguridad de la información para establecer su alcance. Al determinar este alcance, la organización debe considerar: a) las cuestiones externas e internas a que se refiere el 4.1; b) los requisitos a que se refiere el 4.2; c) interfaces y dependencias entre las actividades realizadas por la organización y aquellas que son realizadas por otras organizaciones. El alcance debe estar disponible como información documentada.' WHERE "N_REQUIREMENT_ID_PK" = 5;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe determinar los problemas externos e internos que sean relevantes para su propósito y que afecten su capacidad para lograr los resultados esperados de su sistema de gestión de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 6;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Partes interesadas que son relevantes para el sistema de gestión de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 7;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe determinar los límites y la aplicabilidad del sistema de gestión de la seguridad de la información para establecer su alcance. Al determinar este alcance, la organización debe considerar: a) las cuestiones externas e internas a que se refiere el 4.1; b) los requisitos a que se refiere el 4.2; c) interfaces y dependencias entre las actividades realizadas por la organización y aquellas que son realizadas por otras organizaciones. El alcance debe estar disponible como información documentada.' WHERE "N_REQUIREMENT_ID_PK" = 11;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Garantizar que la política de seguridad de la información y los objetivos de seguridad de la información estén establecidos y sean compatibles con la dirección estratégica de la organización.' WHERE "N_REQUIREMENT_ID_PK" = 12;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe establecer, implementar, mantener y mejorar continuamente un sistema de gestión de la seguridad de la información, incluidos los procesos necesarios y sus interacciones, de acuerdo con los requisitos de este documento.' WHERE "N_REQUIREMENT_ID_PK" = 17;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe establecer, implementar, mantener y mejorar continuamente un sistema de gestión de la seguridad de la información, incluidos los procesos necesarios y sus interacciones, de acuerdo con los requisitos de este documento.' WHERE "N_REQUIREMENT_ID_PK" = 18;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Garantizar la integración de los requisitos del sistema de gestión de seguridad de la información en los procesos de la organización.' WHERE "N_REQUIREMENT_ID_PK" = 19;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Asegurar que los recursos necesarios para el sistema de gestión de seguridad de la información estén disponibles.' WHERE "N_REQUIREMENT_ID_PK" = 20;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Comunicar la importancia de una gestión eficaz de la seguridad de la información y de cumplir con los requisitos del sistema de gestión de la seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 21;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Garantizar que el sistema de gestión de la seguridad de la información logre los resultados previstos.' WHERE "N_REQUIREMENT_ID_PK" = 22;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Dirigir y apoyar a las personas para que contribuyan a la eficacia del sistema de gestión de la seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 23;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Promover la mejora continua.' WHERE "N_REQUIREMENT_ID_PK" = 24;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Apoyar a otros roles gerenciales relevantes para demostrar su liderazgo en lo que se refiere a sus áreas de responsabilidad.' WHERE "N_REQUIREMENT_ID_PK" = 25;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Ser apropiada para el propósito de la organización.' WHERE "N_REQUIREMENT_ID_PK" = 27;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Incluir objetivos de seguridad de la información (ver 6.2) o proporcionar el marco para establecer objetivos de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 28;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Incluir un compromiso de satisfacer los requisitos aplicables relacionados con la seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 29;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Incluir un compromiso de mejora continua del sistema de gestión de la seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 30;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Estar disponible como información documentada.' WHERE "N_REQUIREMENT_ID_PK" = 31;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Ser comunicada dentro de la organización.' WHERE "N_REQUIREMENT_ID_PK" = 32;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Estar a disposición de los interesados, según corresponda.' WHERE "N_REQUIREMENT_ID_PK" = 33;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La alta dirección debe asegurarse de que las responsabilidades y autoridades de los roles relevantes para la seguridad de la información se asignen y comuniquen dentro de la organización. La alta dirección debe asignar la responsabilidad y autoridad para garantizar que el sistema de gestión de la seguridad de la información se ajuste a los requisitos de este documento.' WHERE "N_REQUIREMENT_ID_PK" = 35;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Informar sobre el desempeño del sistema de gestión de seguridad de la información a la alta dirección.' WHERE "N_REQUIREMENT_ID_PK" = 36;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Establecer y mantener criterios de riesgo de seguridad de la información que incluyan los criterios de aceptación de los riesgos y los criterios para realizar evaluaciones de riesgos de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 41;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Al planificar el sistema de gestión de la seguridad de la información, la organización debe tener en cuenta las cuestiones a las que se hace referencia en 4.1 y los requisitos a que se refiere el 4.2, y determinar los riesgos y oportunidades que deben abordarse para: a) garantizar que el sistema de gestión de la seguridad de la información pueda lograr los resultados previstos; b) prevenir o reducir los efectos no deseados.' WHERE "N_REQUIREMENT_ID_PK" = 42;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Lograr la mejora continua.' WHERE "N_REQUIREMENT_ID_PK" = 43;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe planificar acciones para abordar estos riesgos y oportunidades.' WHERE "N_REQUIREMENT_ID_PK" = 47;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe planificar cómo integrar e implementar las acciones en sus procesos del sistema de gestión de seguridad de la información, y cómo evaluar la efectividad de estas acciones.' WHERE "N_REQUIREMENT_ID_PK" = 48;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe definir y aplicar un proceso de evaluación de riesgos de seguridad de la información que: a) establece y mantiene criterios de riesgo, incluyendo los criterios de aceptación y para realizar evaluaciones; b) asegura que evaluaciones repetidas produzcan resultados consistentes, válidos y comparables; c) identifica los riesgos asociados a la pérdida de confidencialidad, integridad y disponibilidad dentro del alcance del SGSI, e identifica a los propietarios del riesgo; d) analiza los riesgos, evaluando consecuencias potenciales, probabilidad de ocurrencia y determinando niveles de riesgo; e) evalúa los riesgos comparando el análisis con los criterios establecidos y priorizándolos para el tratamiento. Se debe conservar información documentada sobre este proceso.' WHERE "N_REQUIREMENT_ID_PK" = 49;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Establecer y mantener criterios de riesgo de seguridad de la información que incluyan los criterios de aceptación de los riesgos y los criterios para realizar evaluaciones de riesgos de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 50;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe definir y aplicar un proceso de tratamiento de riesgos de seguridad de la información para: a) seleccionar opciones apropiadas, teniendo en cuenta los resultados de la evaluación de riesgos; b) determinar todos los controles necesarios para implementar las opciones elegidas; c) comparar los controles determinados con los del Anexo A y verificar que no se hayan omitido controles necesarios; d) producir una Declaración de Aplicabilidad que contenga los controles necesarios, la justificación de su inclusión, si se aplican o no, y la justificación para excluir controles del Anexo A; e) formular un plan de tratamiento de riesgos; y f) obtener la aprobación de los propietarios de riesgos del plan y la aceptación de los riesgos residuales. Se debe conservar información documentada sobre este proceso.' WHERE "N_REQUIREMENT_ID_PK" = 51;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe establecer objetivos de seguridad de la información en las funciones y niveles pertinentes. Los objetivos de seguridad de la información deberán ser coherentes con la política de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 52;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Los objetivos de seguridad de la información deberán ser medibles, si es factible.' WHERE "N_REQUIREMENT_ID_PK" = 54;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Los objetivos de seguridad de la información deberán tener en cuenta los requisitos de seguridad de la información aplicables y los resultados de la evaluación y el tratamiento del riesgo.' WHERE "N_REQUIREMENT_ID_PK" = 55;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Los objetivos de seguridad de la información deberán ser comunicados.' WHERE "N_REQUIREMENT_ID_PK" = 56;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Los objetivos de seguridad de la información deberán actualizarse según corresponda y estar disponibles como información documentada. La organización debe conservar información documentada sobre los objetivos de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 57;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Al planificar cómo lograr sus objetivos de seguridad de la información, la organización debe determinar qué se hará.' WHERE "N_REQUIREMENT_ID_PK" = 58;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Al planificar cómo lograr sus objetivos de seguridad de la información, la organización debe determinar qué recursos se requerirán.' WHERE "N_REQUIREMENT_ID_PK" = 59;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Al planificar cómo lograr sus objetivos de seguridad de la información, la organización debe determinar quién será responsable.' WHERE "N_REQUIREMENT_ID_PK" = 60;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Al planificar cómo lograr sus objetivos de seguridad de la información, la organización debe determinar cuándo se completará.' WHERE "N_REQUIREMENT_ID_PK" = 61;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Al planificar cómo lograr sus objetivos de seguridad de la información, la organización debe determinar cómo se evaluarán los resultados.' WHERE "N_REQUIREMENT_ID_PK" = 62;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe determinar y proporcionar los recursos necesarios para el establecimiento, implementación, mantenimiento y mejora continua del sistema de gestión de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 63;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe determinar la necesidad de comunicaciones internas y externas relevantes para el sistema de gestión de la seguridad de la información, incluyendo: a) sobre qué comunicar; b) cuándo comunicar; c) con quién comunicarse; d) cómo comunicarse.' WHERE "N_REQUIREMENT_ID_PK" = 66;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe determinar y proporcionar los recursos necesarios para el establecimiento, implementación, mantenimiento y mejora continua del sistema de gestión de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 68;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Determinar la competencia necesaria de la(s) persona(s) que realiza(n) el trabajo bajo su control que afecta su desempeño en seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 69;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Garantizar que estas personas sean competentes sobre la base de una educación, formación o experiencia adecuadas.' WHERE "N_REQUIREMENT_ID_PK" = 70;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'En su caso, tomar acciones para adquirir la competencia necesaria y evaluar la efectividad de las acciones tomadas.' WHERE "N_REQUIREMENT_ID_PK" = 71;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Conservar la información documentada apropiada como evidencia de competencia.' WHERE "N_REQUIREMENT_ID_PK" = 72;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Las personas que realicen trabajos bajo el control de la organización deberán ser conscientes de la política de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 73;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Su contribución a la eficacia del sistema de gestión de la seguridad de la información, incluidos los beneficios de un mejor desempeño de la seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 74;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Las implicaciones de no cumplir con los requisitos del sistema de gestión de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 75;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe determinar la necesidad de comunicaciones internas y externas relevantes para el sistema de gestión de la seguridad de la información, incluyendo: a) sobre qué comunicar; b) cuándo comunicar; c) con quién comunicarse; d) cómo comunicarse.' WHERE "N_REQUIREMENT_ID_PK" = 76;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'El sistema de gestión de la seguridad de la información de la organización debe incluir: a) información documentada requerida por este documento; y b) información documentada determinada por la organización como necesaria para la eficacia del sistema de gestión de la seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 77;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Al crear y actualizar la información documentada, la organización debe garantizar lo siguiente: a) identificación y descripción (por ejemplo, un título, fecha, autor o número de referencia); b) formato (por ejemplo, idioma, versión de software, gráficos) y soporte (por ejemplo, papel, electrónico); y c) revisión y aprobación de la idoneidad y adecuación.' WHERE "N_REQUIREMENT_ID_PK" = 78;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La información documentada requerida por el sistema de gestión de seguridad de la información y por este documento se controlará para garantizar que: a) esté disponible y sea adecuada para su uso, donde y cuando se necesite; y b) esté adecuadamente protegida (por ejemplo, contra la pérdida de confidencialidad, uso indebido o pérdida de integridad). Para el control de la información documentada, la organización debe abordar las siguientes actividades, según corresponda: c) distribución, acceso, recuperación y uso; d) almacenamiento y conservación, incluida la conservación de la legibilidad; e) control de cambios (por ejemplo, control de versiones); y f) retención y disposición. La información documentada de origen externo, determinada por la organización como necesaria para la planificación y operación del sistema de gestión de seguridad de la información, debe identificarse según corresponda y controlarse.' WHERE "N_REQUIREMENT_ID_PK" = 79;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe planificar, implementar y controlar los procesos necesarios para cumplir con los requisitos y para implementar las acciones determinadas en la Cláusula 6, mediante el establecimiento de criterios para los procesos y la implementación del control de los procesos de acuerdo con dichos criterios.' WHERE "N_REQUIREMENT_ID_PK" = 83;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La información documentada deberá estar disponible en la medida necesaria para tener confianza en que los procesos se han llevado a cabo según lo planeado.' WHERE "N_REQUIREMENT_ID_PK" = 84;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe controlar los cambios planificados y revisar las consecuencias de los cambios no deseados, tomando medidas para mitigar cualquier efecto adverso, según sea necesario.' WHERE "N_REQUIREMENT_ID_PK" = 85;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe garantizar que los procesos, productos o servicios proporcionados externamente que sean relevantes para el sistema de gestión de la seguridad de la información estén controlados.' WHERE "N_REQUIREMENT_ID_PK" = 86;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe realizar evaluaciones de riesgos de seguridad de la información a intervalos planificados o cuando se propongan o ocurran cambios significativos, teniendo en cuenta los criterios establecidos en 6.1.2 a).' WHERE "N_REQUIREMENT_ID_PK" = 87;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe conservar información documentada de los resultados de las evaluaciones de riesgos de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 88;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe implementar el plan de tratamiento de riesgos de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 89;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe conservar información documentada de los resultados del tratamiento de riesgos de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 90;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La alta dirección debe revisar el sistema de gestión de la seguridad de la información de la organización a intervalos planificados para garantizar su idoneidad, adecuación y eficacia continuas.' WHERE "N_REQUIREMENT_ID_PK" = 93;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Determinar lo que debe monitorearse y medirse, incluidos los procesos y controles de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 94;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Determinar los métodos de seguimiento, medición, análisis y evaluación, según corresponda, para garantizar la validez de los resultados. Los métodos seleccionados deben producir resultados comparables y reproducibles para que se consideren válidos.' WHERE "N_REQUIREMENT_ID_PK" = 95;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Determinar cuándo se realizará el seguimiento y la medición.' WHERE "N_REQUIREMENT_ID_PK" = 96;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Determinar quién deberá monitorear y medir.' WHERE "N_REQUIREMENT_ID_PK" = 97;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Determinar cuándo se analizarán y evaluarán los resultados del seguimiento y la medición.' WHERE "N_REQUIREMENT_ID_PK" = 98;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Determinar quién analizará y evaluará estos resultados. La información documentada deberá estar disponible como evidencia de los resultados. La organización debe evaluar el desempeño de la seguridad de la información y la eficacia del sistema de gestión de la seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 99;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Los requisitos propios de la organización para su sistema de gestión de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 100;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Los requisitos de este documento, y que el sistema de gestión de la seguridad de la información se implemente y mantenga de manera efectiva.' WHERE "N_REQUIREMENT_ID_PK" = 101;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe planificar, establecer, implementar y mantener uno o varios programas de auditoría, incluida la frecuencia, los métodos, las responsabilidades, los requisitos de planificación y la elaboración de informes. Al establecer los programas de auditoría interna, la organización debe considerar la importancia de los procesos en cuestión y los resultados de auditorías anteriores.' WHERE "N_REQUIREMENT_ID_PK" = 102;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Definir los criterios de auditoría y el alcance de cada auditoría.' WHERE "N_REQUIREMENT_ID_PK" = 103;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Seleccionar auditores y realizar auditorías que garanticen la objetividad y la imparcialidad del proceso de auditoría.' WHERE "N_REQUIREMENT_ID_PK" = 104;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Asegurarse de que los resultados de las auditorías se informen a la dirección pertinente.' WHERE "N_REQUIREMENT_ID_PK" = 105;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La información documentada deberá estar disponible como evidencia de la implementación del programa(s) de auditoría y los resultados de la auditoría.' WHERE "N_REQUIREMENT_ID_PK" = 106;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'El estado de las acciones de revisiones de gestión anteriores.' WHERE "N_REQUIREMENT_ID_PK" = 107;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Cambios en cuestiones externas e internas que son relevantes para el sistema de gestión de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 108;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Retroalimentación sobre el desempeño de la seguridad de la información, incluidas las tendencias en no conformidades y acciones correctivas, resultados de monitoreo y medición, resultados de la auditoría, y cumplimiento de los objetivos de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 109;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Retroalimentación de las partes interesadas.' WHERE "N_REQUIREMENT_ID_PK" = 110;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Resultados de la evaluación de riesgos y estado del plan de tratamiento de riesgos.' WHERE "N_REQUIREMENT_ID_PK" = 111;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Oportunidades de mejora continua. Los resultados de la revisión por la dirección incluirán decisiones relacionadas con las oportunidades de mejora continua y cualquier necesidad de cambios en el sistema de gestión de la seguridad de la información. La información documentada deberá estar disponible como evidencia de los resultados de las revisiones por la dirección.' WHERE "N_REQUIREMENT_ID_PK" = 112;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Cuando ocurre una no conformidad, la organización debe reaccionar a la no conformidad y, según corresponda, tomar acciones para controlarla y corregirla, y hacer frente a las consecuencias.' WHERE "N_REQUIREMENT_ID_PK" = 113;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe mejorar continuamente la idoneidad, adecuación y eficacia del sistema de gestión de la seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 114;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Realizar las correcciones ante las no conformidades detectadas, tomando acciones para controlarlas y corregirlas, y hacer frente a las consecuencias.' WHERE "N_REQUIREMENT_ID_PK" = 115;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Evaluar la necesidad de acción para eliminar las causas de la no conformidad, a fin de que no se repita u ocurra en otro lugar, revisando la no conformidad y determinando sus causas.' WHERE "N_REQUIREMENT_ID_PK" = 116;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Implementar cualquier acción correctiva necesaria.' WHERE "N_REQUIREMENT_ID_PK" = 117;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Revisar la efectividad de cualquier acción correctiva tomada.' WHERE "N_REQUIREMENT_ID_PK" = 119;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Realizar cambios en el sistema de gestión de seguridad de la información, si es necesario. Las acciones correctivas deben ser apropiadas a los efectos de las no conformidades encontradas.' WHERE "N_REQUIREMENT_ID_PK" = 120;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Mantener información documentada como evidencia de la naturaleza de las no conformidades y cualquier acción posterior tomada.' WHERE "N_REQUIREMENT_ID_PK" = 121;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Mantener información documentada como evidencia de los resultados de cualquier acción correctiva.' WHERE "N_REQUIREMENT_ID_PK" = 122;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'La organización debe mejorar continuamente la idoneidad, adecuación y eficacia del sistema de gestión de la seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 123;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Los requisitos pertinentes de estas partes interesadas.' WHERE "N_REQUIREMENT_ID_PK" = 127;
UPDATE "MAE_REQUIREMENT" SET "C_DESCRIPTION" = 'Cuál de estos requisitos se abordará a través del sistema de gestión de seguridad de la información.' WHERE "N_REQUIREMENT_ID_PK" = 128;

COMMIT;

-- Verificacion post-ejecucion: cuantas clausulas de ISO 27001 (4-10) siguen sin descripcion.
-- El numero esperado (20) son las filas contenedoras sin texto propio en la norma, detalladas
-- arriba -- no es un error.
SELECT count(*) as sin_descripcion_ok_son_contenedoras
FROM "MAE_REQUIREMENT"
WHERE "N_STANDARD_ID" = 4 AND "N_IS_DELETED" IS DISTINCT FROM true
  AND ("C_DESCRIPTION" IS NULL OR "C_DESCRIPTION" = '');
