-- =====================================================================
-- Seed: riesgos por defecto sugeridos para cada control del Anexo A (ISO 27001)
-- Carga: MAE_VULNERABILITY_TYPE (2 nuevos tipos: Personal, Lugar), MAE_MENACE,
--        MAE_VULNERABILITY, MAE_DEFAULT_RISK, MAE_CONTROL_IN_DEFAULT_RISK
-- Alcance: standardId = 4 (ISO 27001), companyId = 1 (ONPE),
--          93 controles del Anexo A (37 organizacionales, 8 de personas,
--          14 físicos, 34 tecnológicos)
-- Requiere que ya exista el tipo de vulnerabilidad 'Organización' (creado por
-- seed_requirement_default_risks.sql); si no se ha corrido ese script antes,
-- ejecutar primero ese, o ajustar este script para crear también ese tipo.
-- Generado para revisión manual antes de ejecutar contra Railway/Postgres
-- =====================================================================

BEGIN;

-- 1) Nuevos tipos de vulnerabilidad para brechas de personal y de lugar/físicas
WITH new_vuln_types AS (
  INSERT INTO "MAE_VULNERABILITY_TYPE" ("C_NAME", "N_COMPANY_ID", "N_CREATION_USER_ID", "D_CREATION_DATE", "N_IS_DELETED")
  VALUES ('Personal', 1, 1, now(), false), ('Lugar', 1, 1, now(), false)
  RETURNING "N_VULNERABILITY_TYPE_ID_PK", "C_NAME"
),

-- 2) Amenazas (menaces)
new_menaces AS (
  INSERT INTO "MAE_MENACE" ("C_NAME", "N_MENACE_TYPE_ID_FK", "N_COMPANY_ID", "N_CREATION_USER_ID", "D_CREATION_DATE", "N_IS_DELETED")
  VALUES
    ('Ausencia de directrices de seguridad de la información aprobadas por la dirección', 6, 1, 1, now(), false),
    ('Roles y responsabilidades de seguridad de la información no asignados', 6, 1, 1, now(), false),
    ('Abuso de privilegios por concentración de funciones incompatibles', 4, 1, 1, now(), false),
    ('Responsabilidades de seguridad no actualizadas tras cambios organizacionales', 6, 1, 1, now(), false),
    ('Coordinación tardía o inexistente con autoridades ante incidentes', 6, 1, 1, now(), false),
    ('Desactualización frente a nuevas amenazas por aislamiento de la organización', 6, 1, 1, now(), false),
    ('Explotación de amenazas emergentes no identificadas oportunamente', 6, 1, 1, now(), false),
    ('Ejecución de proyectos sin considerar requisitos de seguridad de la información', 6, 1, 1, now(), false),
    ('Pérdida o uso indebido de activos de información no identificados', 6, 1, 1, now(), false),
    ('Uso indebido de la información y otros activos asociados', 4, 1, 1, now(), false),
    ('Fuga de información por activos no devueltos al finalizar la relación laboral o contractual', 4, 1, 1, now(), false),
    ('Divulgación de información sensible por ausencia de clasificación', 6, 1, 1, now(), false),
    ('Manejo inadecuado de información por falta de etiquetado según su clasificación', 6, 1, 1, now(), false),
    ('Interceptación o pérdida de información durante su transferencia', 3, 1, 1, now(), false),
    ('Acceso no autorizado a la información y los sistemas', 2, 1, 1, now(), false),
    ('Suplantación de identidad por gestión deficiente de identidades digitales', 2, 1, 1, now(), false),
    ('Compromiso de credenciales por gestión inadecuada de la información de autenticación', 2, 1, 1, now(), false),
    ('Privilegios de acceso excesivos o no revisados periódicamente', 2, 1, 1, now(), false),
    ('Brechas de seguridad originadas por proveedores', 6, 1, 1, now(), false),
    ('Incumplimiento de obligaciones de seguridad por parte de proveedores', 6, 1, 1, now(), false),
    ('Compromiso de la cadena de suministro de tecnología de la información', 6, 1, 1, now(), false),
    ('Cambios no controlados en los servicios prestados por proveedores', 6, 1, 1, now(), false),
    ('Uso inseguro de servicios en la nube', 3, 1, 1, now(), false),
    ('Respuesta desorganizada o tardía ante incidentes de seguridad de la información', 6, 1, 1, now(), false),
    ('Pérdida de aprendizaje organizacional y evidencia tras incidentes de seguridad', 6, 1, 1, now(), false),
    ('Pérdida de continuidad de la seguridad de la información durante interrupciones', 6, 1, 1, now(), false),
    ('Indisponibilidad de sistemas críticos por desastres o interrupciones prolongadas', 5, 1, 1, now(), false),
    ('Incumplimiento de requisitos legales, reglamentarios o contractuales de seguridad', 6, 1, 1, now(), false),
    ('Infracción de derechos de propiedad intelectual', 6, 1, 1, now(), false),
    ('Pérdida, alteración o divulgación no autorizada de registros', 6, 1, 1, now(), false),
    ('Incumplimiento de la normativa de protección de datos personales', 6, 1, 1, now(), false),
    ('Deficiencias del SGSI no detectadas por falta de revisión independiente', 6, 1, 1, now(), false),
    ('Incumplimiento interno de las políticas y estándares de seguridad de la información', 4, 1, 1, now(), false),
    ('Errores operativos por ejecución no estandarizada de procedimientos', 6, 1, 1, now(), false),
    ('Vinculación de personal sin verificación de antecedentes adecuada', 4, 1, 1, now(), false),
    ('Incumplimiento de obligaciones de seguridad por falta de cláusulas contractuales claras', 4, 1, 1, now(), false),
    ('Error humano por falta de concientización, educación y capacitación en seguridad', 4, 1, 1, now(), false),
    ('Reincidencia de incumplimientos por ausencia de consecuencias formales', 4, 1, 1, now(), false),
    ('Accesos o información retenida indebidamente tras la finalización del empleo', 4, 1, 1, now(), false),
    ('Divulgación no autorizada de información confidencial por el personal o terceros', 4, 1, 1, now(), false),
    ('Exposición de información en modalidades de trabajo remoto no seguras', 4, 1, 1, now(), false),
    ('Eventos de seguridad no reportados oportunamente por el personal', 4, 1, 1, now(), false),
    ('Acceso físico no autorizado a las instalaciones', 5, 1, 1, now(), false),
    ('Ingreso no controlado de personas a áreas restringidas', 5, 1, 1, now(), false),
    ('Exposición de información en oficinas, salas o instalaciones no aseguradas', 5, 1, 1, now(), false),
    ('Incidentes físicos no detectados por falta de monitoreo', 5, 1, 1, now(), false),
    ('Daño a instalaciones o equipos por amenazas físicas o ambientales', 5, 1, 1, now(), false),
    ('Exposición de información en áreas seguras por controles de trabajo inadecuados', 5, 1, 1, now(), false),
    ('Exposición de información por escritorios o pantallas desprotegidos', 4, 1, 1, now(), false),
    ('Daño o pérdida de equipos por emplazamiento inadecuado', 1, 1, 1, now(), false),
    ('Pérdida o robo de activos fuera de las instalaciones de la organización', 1, 1, 1, now(), false),
    ('Fuga o pérdida de información por gestión inadecuada de medios de almacenamiento', 1, 1, 1, now(), false),
    ('Interrupción de servicios por falla de utilidades de apoyo (energía, climatización)', 5, 1, 1, now(), false),
    ('Interceptación o daño de datos por cableado no protegido', 1, 1, 1, now(), false),
    ('Falla de equipos por mantenimiento insuficiente', 1, 1, 1, now(), false),
    ('Fuga de información al eliminar o reutilizar equipos sin borrado seguro', 1, 1, 1, now(), false),
    ('Compromiso de información en dispositivos de usuario final no protegidos', 1, 1, 1, now(), false),
    ('Abuso de privilegios por gestión inadecuada de accesos privilegiados', 2, 1, 1, now(), false),
    ('Acceso no autorizado a la información por restricciones de acceso insuficientes', 2, 1, 1, now(), false),
    ('Manipulación no autorizada del código fuente', 2, 1, 1, now(), false),
    ('Compromiso de cuentas por mecanismos de autenticación débiles', 2, 1, 1, now(), false),
    ('Degradación o caída de servicios por capacidad de recursos insuficiente', 1, 1, 1, now(), false),
    ('Infección de malware en los sistemas de información', 2, 1, 1, now(), false),
    ('Explotación de vulnerabilidades técnicas no identificadas ni corregidas', 2, 1, 1, now(), false),
    ('Configuraciones inseguras o no estandarizadas en los sistemas', 2, 1, 1, now(), false),
    ('Recuperación no autorizada de información eliminada de forma insegura', 2, 1, 1, now(), false),
    ('Exposición de datos sensibles en entornos no productivos', 2, 1, 1, now(), false),
    ('Fuga de datos sensibles fuera de la organización', 2, 1, 1, now(), false),
    ('Pérdida irrecuperable de información por ausencia o falla de copias de seguridad', 2, 1, 1, now(), false),
    ('Interrupción del servicio por falta de redundancia en las instalaciones de procesamiento', 1, 1, 1, now(), false),
    ('Actividad maliciosa no detectada por ausencia de registros (logs) de eventos', 2, 1, 1, now(), false),
    ('Falta de monitoreo continuo de la actividad de los sistemas', 2, 1, 1, now(), false),
    ('Trazabilidad de eventos comprometida por desincronización de relojes', 2, 1, 1, now(), false),
    ('Uso indebido de herramientas de administración con privilegios elevados', 2, 1, 1, now(), false),
    ('Instalación de software no autorizado o malicioso en los sistemas operativos', 2, 1, 1, now(), false),
    ('Acceso no autorizado a la red por controles de red insuficientes', 3, 1, 1, now(), false),
    ('Compromiso de servicios de red inseguros o mal configurados', 3, 1, 1, now(), false),
    ('Propagación de incidentes entre segmentos de red por falta de segregación', 3, 1, 1, now(), false),
    ('Acceso a contenido malicioso por navegación web sin restricciones', 3, 1, 1, now(), false),
    ('Exposición de información sensible por ausencia o debilidad de controles criptográficos', 2, 1, 1, now(), false),
    ('Vulnerabilidades introducidas por un ciclo de desarrollo de software inseguro', 2, 1, 1, now(), false),
    ('Desarrollo o adquisición de aplicaciones sin requisitos de seguridad definidos', 2, 1, 1, now(), false),
    ('Diseño de sistemas sin principios de arquitectura de seguridad', 2, 1, 1, now(), false),
    ('Explotación de vulnerabilidades por prácticas de codificación insegura', 2, 1, 1, now(), false),
    ('Despliegue de software con vulnerabilidades no detectadas por falta de pruebas de seguridad', 2, 1, 1, now(), false),
    ('Vulnerabilidades introducidas por desarrollo subcontratado sin supervisión de seguridad', 2, 1, 1, now(), false),
    ('Contaminación de datos de producción por mezcla de entornos de desarrollo, prueba y producción', 2, 1, 1, now(), false),
    ('Incidentes causados por cambios no controlados en los sistemas', 2, 1, 1, now(), false),
    ('Exposición de datos reales sensibles utilizados como información de prueba', 2, 1, 1, now(), false),
    ('Interrupción o daño de sistemas de producción durante actividades de auditoría o pruebas', 2, 1, 1, now(), false)
  RETURNING "N_MENACE_ID_PK", "C_NAME"
),

-- 3) Vulnerabilidades (usa el tipo existente 'Organización' y los 2 nuevos tipos 'Personal'/'Lugar')
vuln_type_lookup AS (
  SELECT "N_VULNERABILITY_TYPE_ID_PK", "C_NAME" FROM "MAE_VULNERABILITY_TYPE" WHERE "C_NAME" IN ('Organización', 'Hardware', 'Software', 'Red')
  UNION ALL
  SELECT "N_VULNERABILITY_TYPE_ID_PK", "C_NAME" FROM new_vuln_types
),
vuln_pairs (name, type_name) AS (
  VALUES
    ('Ausencia de políticas de seguridad de la información aprobadas y publicadas', 'Organización'),
    ('Roles y responsabilidades de seguridad de la información no definidos formalmente', 'Organización'),
    ('Ausencia de segregación de funciones en procesos críticos', 'Organización'),
    ('Falta de actualización de responsabilidades de seguridad ante cambios organizacionales', 'Organización'),
    ('Ausencia de un procedimiento de contacto con autoridades competentes', 'Organización'),
    ('Falta de participación en foros o grupos especializados en seguridad de la información', 'Organización'),
    ('Ausencia de un proceso de inteligencia de amenazas', 'Organización'),
    ('Falta de integración de requisitos de seguridad en la gestión de proyectos', 'Organización'),
    ('Ausencia de un inventario actualizado de información y activos asociados', 'Organización'),
    ('Falta de reglas de uso aceptable de la información y los activos', 'Organización'),
    ('Ausencia de un procedimiento de devolución de activos al finalizar la relación laboral', 'Organización'),
    ('Ausencia de un esquema de clasificación de información', 'Organización'),
    ('Falta de etiquetado de la información según su clasificación', 'Organización'),
    ('Ausencia de controles para la transferencia segura de información', 'Red'),
    ('Ausencia de una política de control de accesos', 'Software'),
    ('Gestión deficiente del ciclo de vida de identidades digitales', 'Software'),
    ('Gestión inadecuada de la información de autenticación (contraseñas, tokens, etc.)', 'Software'),
    ('Ausencia de revisión periódica de derechos de acceso', 'Software'),
    ('Falta de requisitos de seguridad establecidos para proveedores', 'Organización'),
    ('Ausencia de cláusulas de seguridad de la información en los acuerdos con proveedores', 'Organización'),
    ('Falta de gestión de riesgos en la cadena de suministro TIC', 'Organización'),
    ('Ausencia de monitoreo y revisión de los servicios prestados por proveedores', 'Organización'),
    ('Falta de criterios de seguridad para el uso de servicios en la nube', 'Red'),
    ('Ausencia de un proceso formal de gestión de incidentes de seguridad de la información', 'Organización'),
    ('Falta de mecanismos para capitalizar el aprendizaje y preservar evidencias de incidentes', 'Organización'),
    ('Ausencia de planes de continuidad de seguridad de la información ante interrupciones', 'Organización'),
    ('Falta de preparación de las TIC para la continuidad del negocio', 'Software'),
    ('Ausencia de un proceso de identificación de requisitos legales y contractuales', 'Organización'),
    ('Falta de control sobre el uso de material protegido por derechos de propiedad intelectual', 'Organización'),
    ('Ausencia de controles de protección de registros contra pérdida o alteración', 'Organización'),
    ('Falta de un procedimiento de privacidad y protección de datos personales', 'Organización'),
    ('Ausencia de revisiones independientes periódicas del SGSI', 'Organización'),
    ('Falta de verificación del cumplimiento de políticas y estándares de seguridad', 'Organización'),
    ('Ausencia de procedimientos operativos documentados', 'Organización'),
    ('Falta de verificación de antecedentes en el proceso de selección de personal', 'Organización'),
    ('Ausencia de cláusulas de seguridad en los términos y condiciones de empleo', 'Organización'),
    ('Falta de un programa de concientización, educación y capacitación en seguridad', 'Organización'),
    ('Ausencia de un proceso disciplinario formal ante incumplimientos', 'Organización'),
    ('Falta de un procedimiento de responsabilidades tras la terminación del empleo', 'Organización'),
    ('Ausencia de acuerdos de confidencialidad o no divulgación con el personal y terceros', 'Organización'),
    ('Falta de controles de seguridad definidos para el trabajo remoto', 'Organización'),
    ('Ausencia de canales definidos para reportar eventos de seguridad de la información', 'Organización'),
    ('Ausencia de un perímetro de seguridad física definido', 'Lugar'),
    ('Falta de controles de entrada física a las instalaciones', 'Lugar'),
    ('Ausencia de medidas para asegurar oficinas, salas e instalaciones', 'Lugar'),
    ('Falta de monitoreo de la seguridad física de las instalaciones', 'Lugar'),
    ('Ausencia de protección contra amenazas físicas y ambientales', 'Lugar'),
    ('Falta de reglas para trabajar en áreas seguras', 'Lugar'),
    ('Ausencia de una política de escritorio y pantalla despejados', 'Organización'),
    ('Emplazamiento y protección inadecuados de los equipos', 'Hardware'),
    ('Falta de controles de seguridad para activos utilizados fuera de las instalaciones', 'Hardware'),
    ('Gestión inadecuada de los medios de almacenamiento', 'Hardware'),
    ('Ausencia de redundancia en las utilidades de apoyo (energía, climatización)', 'Lugar'),
    ('Falta de protección del cableado eléctrico y de datos', 'Hardware'),
    ('Ausencia de un programa de mantenimiento preventivo de equipos', 'Hardware'),
    ('Falta de un procedimiento de eliminación segura o reutilización de equipos', 'Hardware'),
    ('Ausencia de controles de seguridad en dispositivos de usuario final', 'Hardware'),
    ('Gestión inadecuada de los derechos de acceso privilegiado', 'Software'),
    ('Restricciones de acceso a la información insuficientes o mal aplicadas', 'Software'),
    ('Falta de control de acceso al código fuente de las aplicaciones', 'Software'),
    ('Ausencia de mecanismos de autenticación segura (multifactor, robusta)', 'Software'),
    ('Falta de gestión y planificación de la capacidad de los recursos tecnológicos', 'Hardware'),
    ('Ausencia de protección antimalware actualizada', 'Software'),
    ('Ausencia de un proceso de gestión de vulnerabilidades técnicas', 'Software'),
    ('Falta de estandarización y control de la configuración de los sistemas', 'Software'),
    ('Ausencia de procedimientos de eliminación segura de la información', 'Software'),
    ('Falta de enmascaramiento de datos sensibles en entornos no productivos', 'Software'),
    ('Ausencia de controles de prevención de fuga de datos (DLP)', 'Software'),
    ('Ausencia o falla de un procedimiento de copias de seguridad', 'Software'),
    ('Falta de redundancia en las instalaciones de procesamiento de información', 'Hardware'),
    ('Ausencia de registros (logs) de inicio de sesión y eventos', 'Software'),
    ('Falta de monitoreo de la actividad de seguimiento de los sistemas', 'Software'),
    ('Ausencia de sincronización de reloj entre los sistemas', 'Software'),
    ('Uso no controlado de programas de utilidad con privilegios elevados', 'Software'),
    ('Ausencia de control sobre la instalación de software en sistemas operativos', 'Software'),
    ('Controles de red insuficientes o mal configurados', 'Red'),
    ('Falta de aseguramiento de los servicios de red', 'Red'),
    ('Ausencia de segregación de redes', 'Red'),
    ('Falta de filtrado y control de acceso a contenido web', 'Red'),
    ('Ausencia o debilidad de controles criptográficos', 'Software'),
    ('Ausencia de un ciclo de vida de desarrollo seguro de software', 'Software'),
    ('Falta de definición de requisitos de seguridad para las aplicaciones', 'Software'),
    ('Ausencia de principios de arquitectura e ingeniería de sistemas seguros', 'Software'),
    ('Falta de estándares de codificación segura', 'Software'),
    ('Ausencia de pruebas de seguridad en el desarrollo y aceptación de software', 'Software'),
    ('Falta de supervisión de seguridad en el desarrollo subcontratado', 'Software'),
    ('Ausencia de separación entre los entornos de desarrollo, prueba y producción', 'Software'),
    ('Ausencia de un procedimiento formal de gestión de cambios', 'Software'),
    ('Uso de datos reales como información de prueba sin protección', 'Software'),
    ('Falta de controles que protejan los sistemas de producción durante auditorías o pruebas', 'Software')
),
new_vulns AS (
  INSERT INTO "MAE_VULNERABILITY" ("C_NAME", "N_VULNERABILITY_TYPE_ID_FK", "N_COMPANY_ID", "N_CREATION_USER_ID", "D_CREATION_DATE", "N_IS_DELETED")
  SELECT vp.name, vt."N_VULNERABILITY_TYPE_ID_PK", 1, 1, now(), false
  FROM vuln_pairs vp
  JOIN vuln_type_lookup vt ON vt."C_NAME" = vp.type_name
  RETURNING "N_VULNERABILITY_ID_PK", "C_NAME"
),

-- 4) Riesgos por defecto (combinación amenaza + vulnerabilidad)
risk_pairs (risk_name, menace_name, vuln_name) AS (
  VALUES
    ('Riesgo por ausencia de políticas de seguridad de la información aprobadas por la dirección', 'Ausencia de directrices de seguridad de la información aprobadas por la dirección', 'Ausencia de políticas de seguridad de la información aprobadas y publicadas'),
    ('Riesgo por roles y responsabilidades de seguridad de la información no definidos', 'Roles y responsabilidades de seguridad de la información no asignados', 'Roles y responsabilidades de seguridad de la información no definidos formalmente'),
    ('Riesgo por conflictos de interés o fraude por falta de segregación de funciones', 'Abuso de privilegios por concentración de funciones incompatibles', 'Ausencia de segregación de funciones en procesos críticos'),
    ('Riesgo por responsabilidades de seguridad no gestionadas tras cambios organizacionales', 'Responsabilidades de seguridad no actualizadas tras cambios organizacionales', 'Falta de actualización de responsabilidades de seguridad ante cambios organizacionales'),
    ('Riesgo por falta de coordinación oportuna con autoridades ante incidentes', 'Coordinación tardía o inexistente con autoridades ante incidentes', 'Ausencia de un procedimiento de contacto con autoridades competentes'),
    ('Riesgo por desactualización frente a nuevas amenazas por falta de contacto con comunidades especializadas', 'Desactualización frente a nuevas amenazas por aislamiento de la organización', 'Falta de participación en foros o grupos especializados en seguridad de la información'),
    ('Riesgo por explotación de amenazas emergentes no identificadas oportunamente', 'Explotación de amenazas emergentes no identificadas oportunamente', 'Ausencia de un proceso de inteligencia de amenazas'),
    ('Riesgo por proyectos ejecutados sin considerar requisitos de seguridad de la información', 'Ejecución de proyectos sin considerar requisitos de seguridad de la información', 'Falta de integración de requisitos de seguridad en la gestión de proyectos'),
    ('Riesgo por activos de información no identificados ni inventariados', 'Pérdida o uso indebido de activos de información no identificados', 'Ausencia de un inventario actualizado de información y activos asociados'),
    ('Riesgo por uso indebido de la información y otros activos asociados', 'Uso indebido de la información y otros activos asociados', 'Falta de reglas de uso aceptable de la información y los activos'),
    ('Riesgo por fuga de información por activos no devueltos al finalizar la relación laboral o contractual', 'Fuga de información por activos no devueltos al finalizar la relación laboral o contractual', 'Ausencia de un procedimiento de devolución de activos al finalizar la relación laboral'),
    ('Riesgo por divulgación de información sensible por ausencia de clasificación', 'Divulgación de información sensible por ausencia de clasificación', 'Ausencia de un esquema de clasificación de información'),
    ('Riesgo por manejo inadecuado de información por falta de etiquetado', 'Manejo inadecuado de información por falta de etiquetado según su clasificación', 'Falta de etiquetado de la información según su clasificación'),
    ('Riesgo por interceptación o pérdida de información durante su transferencia', 'Interceptación o pérdida de información durante su transferencia', 'Ausencia de controles para la transferencia segura de información'),
    ('Riesgo por acceso no autorizado a la información y los sistemas', 'Acceso no autorizado a la información y los sistemas', 'Ausencia de una política de control de accesos'),
    ('Riesgo por suplantación de identidad por gestión deficiente de identidades digitales', 'Suplantación de identidad por gestión deficiente de identidades digitales', 'Gestión deficiente del ciclo de vida de identidades digitales'),
    ('Riesgo por compromiso de credenciales por gestión inadecuada de la información de autenticación', 'Compromiso de credenciales por gestión inadecuada de la información de autenticación', 'Gestión inadecuada de la información de autenticación (contraseñas, tokens, etc.)'),
    ('Riesgo por privilegios de acceso excesivos o no revisados periódicamente', 'Privilegios de acceso excesivos o no revisados periódicamente', 'Ausencia de revisión periódica de derechos de acceso'),
    ('Riesgo por brechas de seguridad originadas por proveedores', 'Brechas de seguridad originadas por proveedores', 'Falta de requisitos de seguridad establecidos para proveedores'),
    ('Riesgo por proveedores sin obligaciones contractuales de seguridad de la información', 'Incumplimiento de obligaciones de seguridad por parte de proveedores', 'Ausencia de cláusulas de seguridad de la información en los acuerdos con proveedores'),
    ('Riesgo por compromiso de la cadena de suministro de tecnología de la información', 'Compromiso de la cadena de suministro de tecnología de la información', 'Falta de gestión de riesgos en la cadena de suministro TIC'),
    ('Riesgo por cambios no controlados en los servicios prestados por proveedores', 'Cambios no controlados en los servicios prestados por proveedores', 'Ausencia de monitoreo y revisión de los servicios prestados por proveedores'),
    ('Riesgo por uso inseguro de servicios en la nube', 'Uso inseguro de servicios en la nube', 'Falta de criterios de seguridad para el uso de servicios en la nube'),
    ('Riesgo por respuesta desorganizada o tardía ante incidentes de seguridad de la información', 'Respuesta desorganizada o tardía ante incidentes de seguridad de la información', 'Ausencia de un proceso formal de gestión de incidentes de seguridad de la información'),
    ('Riesgo por pérdida de aprendizaje organizacional y evidencia tras incidentes de seguridad', 'Pérdida de aprendizaje organizacional y evidencia tras incidentes de seguridad', 'Falta de mecanismos para capitalizar el aprendizaje y preservar evidencias de incidentes'),
    ('Riesgo por pérdida de continuidad de la seguridad de la información durante interrupciones', 'Pérdida de continuidad de la seguridad de la información durante interrupciones', 'Ausencia de planes de continuidad de seguridad de la información ante interrupciones'),
    ('Riesgo por indisponibilidad de sistemas críticos por falta de preparación de continuidad TIC', 'Indisponibilidad de sistemas críticos por desastres o interrupciones prolongadas', 'Falta de preparación de las TIC para la continuidad del negocio'),
    ('Riesgo por incumplimiento de requisitos legales, reglamentarios o contractuales de seguridad', 'Incumplimiento de requisitos legales, reglamentarios o contractuales de seguridad', 'Ausencia de un proceso de identificación de requisitos legales y contractuales'),
    ('Riesgo por infracción de derechos de propiedad intelectual', 'Infracción de derechos de propiedad intelectual', 'Falta de control sobre el uso de material protegido por derechos de propiedad intelectual'),
    ('Riesgo por pérdida, alteración o divulgación no autorizada de registros', 'Pérdida, alteración o divulgación no autorizada de registros', 'Ausencia de controles de protección de registros contra pérdida o alteración'),
    ('Riesgo por incumplimiento de la normativa de protección de datos personales', 'Incumplimiento de la normativa de protección de datos personales', 'Falta de un procedimiento de privacidad y protección de datos personales'),
    ('Riesgo por deficiencias del SGSI no detectadas por falta de revisiones independientes', 'Deficiencias del SGSI no detectadas por falta de revisión independiente', 'Ausencia de revisiones independientes periódicas del SGSI'),
    ('Riesgo por incumplimiento interno de las políticas y estándares de seguridad de la información', 'Incumplimiento interno de las políticas y estándares de seguridad de la información', 'Falta de verificación del cumplimiento de políticas y estándares de seguridad'),
    ('Riesgo por errores operativos por ausencia de procedimientos documentados', 'Errores operativos por ejecución no estandarizada de procedimientos', 'Ausencia de procedimientos operativos documentados'),
    ('Riesgo por contratación de personal sin verificación de antecedentes adecuada', 'Vinculación de personal sin verificación de antecedentes adecuada', 'Falta de verificación de antecedentes en el proceso de selección de personal'),
    ('Riesgo por incumplimiento de obligaciones de seguridad por falta de cláusulas contractuales claras', 'Incumplimiento de obligaciones de seguridad por falta de cláusulas contractuales claras', 'Ausencia de cláusulas de seguridad en los términos y condiciones de empleo'),
    ('Riesgo por error humano por falta de concientización, educación y capacitación en seguridad', 'Error humano por falta de concientización, educación y capacitación en seguridad', 'Falta de un programa de concientización, educación y capacitación en seguridad'),
    ('Riesgo por reincidencia de incumplimientos por ausencia de un proceso disciplinario formal', 'Reincidencia de incumplimientos por ausencia de consecuencias formales', 'Ausencia de un proceso disciplinario formal ante incumplimientos'),
    ('Riesgo por accesos o información retenida indebidamente tras la finalización del empleo', 'Accesos o información retenida indebidamente tras la finalización del empleo', 'Falta de un procedimiento de responsabilidades tras la terminación del empleo'),
    ('Riesgo por divulgación no autorizada de información por ausencia de acuerdos de confidencialidad', 'Divulgación no autorizada de información confidencial por el personal o terceros', 'Ausencia de acuerdos de confidencialidad o no divulgación con el personal y terceros'),
    ('Riesgo por exposición de información en modalidades de trabajo remoto no seguras', 'Exposición de información en modalidades de trabajo remoto no seguras', 'Falta de controles de seguridad definidos para el trabajo remoto'),
    ('Riesgo por eventos de seguridad no reportados oportunamente por el personal', 'Eventos de seguridad no reportados oportunamente por el personal', 'Ausencia de canales definidos para reportar eventos de seguridad de la información'),
    ('Riesgo por acceso físico no autorizado a las instalaciones', 'Acceso físico no autorizado a las instalaciones', 'Ausencia de un perímetro de seguridad física definido'),
    ('Riesgo por ingreso no controlado de personas a áreas restringidas', 'Ingreso no controlado de personas a áreas restringidas', 'Falta de controles de entrada física a las instalaciones'),
    ('Riesgo por exposición de información en oficinas, salas o instalaciones no aseguradas', 'Exposición de información en oficinas, salas o instalaciones no aseguradas', 'Ausencia de medidas para asegurar oficinas, salas e instalaciones'),
    ('Riesgo por incidentes físicos no detectados por falta de monitoreo', 'Incidentes físicos no detectados por falta de monitoreo', 'Falta de monitoreo de la seguridad física de las instalaciones'),
    ('Riesgo por daño a instalaciones o equipos por amenazas físicas o ambientales', 'Daño a instalaciones o equipos por amenazas físicas o ambientales', 'Ausencia de protección contra amenazas físicas y ambientales'),
    ('Riesgo por exposición de información en áreas seguras por controles de trabajo inadecuados', 'Exposición de información en áreas seguras por controles de trabajo inadecuados', 'Falta de reglas para trabajar en áreas seguras'),
    ('Riesgo por exposición de información por escritorios o pantallas desprotegidos', 'Exposición de información por escritorios o pantallas desprotegidos', 'Ausencia de una política de escritorio y pantalla despejados'),
    ('Riesgo por daño o pérdida de equipos por emplazamiento inadecuado', 'Daño o pérdida de equipos por emplazamiento inadecuado', 'Emplazamiento y protección inadecuados de los equipos'),
    ('Riesgo por pérdida o robo de activos fuera de las instalaciones de la organización', 'Pérdida o robo de activos fuera de las instalaciones de la organización', 'Falta de controles de seguridad para activos utilizados fuera de las instalaciones'),
    ('Riesgo por fuga o pérdida de información por gestión inadecuada de medios de almacenamiento', 'Fuga o pérdida de información por gestión inadecuada de medios de almacenamiento', 'Gestión inadecuada de los medios de almacenamiento'),
    ('Riesgo por interrupción de servicios por falla de utilidades de apoyo', 'Interrupción de servicios por falla de utilidades de apoyo (energía, climatización)', 'Ausencia de redundancia en las utilidades de apoyo (energía, climatización)'),
    ('Riesgo por interceptación o daño de datos por cableado no protegido', 'Interceptación o daño de datos por cableado no protegido', 'Falta de protección del cableado eléctrico y de datos'),
    ('Riesgo por falla de equipos por mantenimiento insuficiente', 'Falla de equipos por mantenimiento insuficiente', 'Ausencia de un programa de mantenimiento preventivo de equipos'),
    ('Riesgo por fuga de información al eliminar o reutilizar equipos sin borrado seguro', 'Fuga de información al eliminar o reutilizar equipos sin borrado seguro', 'Falta de un procedimiento de eliminación segura o reutilización de equipos'),
    ('Riesgo por compromiso de información en dispositivos de usuario final no protegidos', 'Compromiso de información en dispositivos de usuario final no protegidos', 'Ausencia de controles de seguridad en dispositivos de usuario final'),
    ('Riesgo por abuso de privilegios por gestión inadecuada de accesos privilegiados', 'Abuso de privilegios por gestión inadecuada de accesos privilegiados', 'Gestión inadecuada de los derechos de acceso privilegiado'),
    ('Riesgo por acceso no autorizado a la información por restricciones de acceso insuficientes', 'Acceso no autorizado a la información por restricciones de acceso insuficientes', 'Restricciones de acceso a la información insuficientes o mal aplicadas'),
    ('Riesgo por manipulación no autorizada del código fuente', 'Manipulación no autorizada del código fuente', 'Falta de control de acceso al código fuente de las aplicaciones'),
    ('Riesgo por compromiso de cuentas por mecanismos de autenticación débiles', 'Compromiso de cuentas por mecanismos de autenticación débiles', 'Ausencia de mecanismos de autenticación segura (multifactor, robusta)'),
    ('Riesgo por degradación o caída de servicios por capacidad de recursos insuficiente', 'Degradación o caída de servicios por capacidad de recursos insuficiente', 'Falta de gestión y planificación de la capacidad de los recursos tecnológicos'),
    ('Riesgo por infección de malware en los sistemas de información', 'Infección de malware en los sistemas de información', 'Ausencia de protección antimalware actualizada'),
    ('Riesgo por explotación de vulnerabilidades técnicas no identificadas ni corregidas', 'Explotación de vulnerabilidades técnicas no identificadas ni corregidas', 'Ausencia de un proceso de gestión de vulnerabilidades técnicas'),
    ('Riesgo por configuraciones inseguras o no estandarizadas en los sistemas', 'Configuraciones inseguras o no estandarizadas en los sistemas', 'Falta de estandarización y control de la configuración de los sistemas'),
    ('Riesgo por recuperación no autorizada de información eliminada de forma insegura', 'Recuperación no autorizada de información eliminada de forma insegura', 'Ausencia de procedimientos de eliminación segura de la información'),
    ('Riesgo por exposición de datos sensibles en entornos no productivos', 'Exposición de datos sensibles en entornos no productivos', 'Falta de enmascaramiento de datos sensibles en entornos no productivos'),
    ('Riesgo por fuga de datos sensibles fuera de la organización', 'Fuga de datos sensibles fuera de la organización', 'Ausencia de controles de prevención de fuga de datos (DLP)'),
    ('Riesgo por pérdida irrecuperable de información por ausencia o falla de copias de seguridad', 'Pérdida irrecuperable de información por ausencia o falla de copias de seguridad', 'Ausencia o falla de un procedimiento de copias de seguridad'),
    ('Riesgo por interrupción del servicio por falta de redundancia en las instalaciones de procesamiento', 'Interrupción del servicio por falta de redundancia en las instalaciones de procesamiento', 'Falta de redundancia en las instalaciones de procesamiento de información'),
    ('Riesgo por actividad maliciosa no detectada por ausencia de registros (logs) de eventos', 'Actividad maliciosa no detectada por ausencia de registros (logs) de eventos', 'Ausencia de registros (logs) de inicio de sesión y eventos'),
    ('Riesgo por falta de monitoreo continuo de la actividad de los sistemas', 'Falta de monitoreo continuo de la actividad de los sistemas', 'Falta de monitoreo de la actividad de seguimiento de los sistemas'),
    ('Riesgo por trazabilidad de eventos comprometida por desincronización de relojes', 'Trazabilidad de eventos comprometida por desincronización de relojes', 'Ausencia de sincronización de reloj entre los sistemas'),
    ('Riesgo por uso indebido de herramientas de administración con privilegios elevados', 'Uso indebido de herramientas de administración con privilegios elevados', 'Uso no controlado de programas de utilidad con privilegios elevados'),
    ('Riesgo por instalación de software no autorizado o malicioso en los sistemas operativos', 'Instalación de software no autorizado o malicioso en los sistemas operativos', 'Ausencia de control sobre la instalación de software en sistemas operativos'),
    ('Riesgo por acceso no autorizado a la red por controles de red insuficientes', 'Acceso no autorizado a la red por controles de red insuficientes', 'Controles de red insuficientes o mal configurados'),
    ('Riesgo por compromiso de servicios de red inseguros o mal configurados', 'Compromiso de servicios de red inseguros o mal configurados', 'Falta de aseguramiento de los servicios de red'),
    ('Riesgo por propagación de incidentes entre segmentos de red por falta de segregación', 'Propagación de incidentes entre segmentos de red por falta de segregación', 'Ausencia de segregación de redes'),
    ('Riesgo por acceso a contenido malicioso por ausencia de filtrado web', 'Acceso a contenido malicioso por navegación web sin restricciones', 'Falta de filtrado y control de acceso a contenido web'),
    ('Riesgo por exposición de información sensible por ausencia o debilidad de controles criptográficos', 'Exposición de información sensible por ausencia o debilidad de controles criptográficos', 'Ausencia o debilidad de controles criptográficos'),
    ('Riesgo por vulnerabilidades introducidas por un ciclo de desarrollo de software inseguro', 'Vulnerabilidades introducidas por un ciclo de desarrollo de software inseguro', 'Ausencia de un ciclo de vida de desarrollo seguro de software'),
    ('Riesgo por aplicaciones desarrolladas o adquiridas sin requisitos de seguridad definidos', 'Desarrollo o adquisición de aplicaciones sin requisitos de seguridad definidos', 'Falta de definición de requisitos de seguridad para las aplicaciones'),
    ('Riesgo por diseño de sistemas sin principios de arquitectura de seguridad', 'Diseño de sistemas sin principios de arquitectura de seguridad', 'Ausencia de principios de arquitectura e ingeniería de sistemas seguros'),
    ('Riesgo por explotación de vulnerabilidades por prácticas de codificación insegura', 'Explotación de vulnerabilidades por prácticas de codificación insegura', 'Falta de estándares de codificación segura'),
    ('Riesgo por despliegue de software con vulnerabilidades no detectadas por falta de pruebas de seguridad', 'Despliegue de software con vulnerabilidades no detectadas por falta de pruebas de seguridad', 'Ausencia de pruebas de seguridad en el desarrollo y aceptación de software'),
    ('Riesgo por vulnerabilidades introducidas por desarrollo subcontratado sin supervisión de seguridad', 'Vulnerabilidades introducidas por desarrollo subcontratado sin supervisión de seguridad', 'Falta de supervisión de seguridad en el desarrollo subcontratado'),
    ('Riesgo por contaminación de datos de producción por falta de separación entre entornos', 'Contaminación de datos de producción por mezcla de entornos de desarrollo, prueba y producción', 'Ausencia de separación entre los entornos de desarrollo, prueba y producción'),
    ('Riesgo por incidentes causados por cambios no controlados en los sistemas', 'Incidentes causados por cambios no controlados en los sistemas', 'Ausencia de un procedimiento formal de gestión de cambios'),
    ('Riesgo por exposición de datos reales sensibles utilizados como información de prueba', 'Exposición de datos reales sensibles utilizados como información de prueba', 'Uso de datos reales como información de prueba sin protección'),
    ('Riesgo por interrupción o daño de sistemas de producción durante actividades de auditoría o pruebas', 'Interrupción o daño de sistemas de producción durante actividades de auditoría o pruebas', 'Falta de controles que protejan los sistemas de producción durante auditorías o pruebas')
),
new_risks AS (
  INSERT INTO "MAE_DEFAULT_RISK" ("C_NAME", "N_STANDARD_ID_FK", "N_MENACE_ID_FK", "N_VULNERABILITY_ID_FK", "N_COMPANY_ID_FK", "N_CREATION_USER_ID", "D_CREATION_DATE", "N_IS_DELETED")
  SELECT rp.risk_name, 4, nm."N_MENACE_ID_PK", nv."N_VULNERABILITY_ID_PK", 1, 1, now(), false
  FROM risk_pairs rp
  JOIN new_menaces nm ON nm."C_NAME" = rp.menace_name
  JOIN new_vulns nv ON nv."C_NAME" = rp.vuln_name
  RETURNING "N_DEFAULT_RISK_ID_PK", "C_NAME"
)

-- 5) Asociación control -> riesgo sugerido (MAE_CONTROL_IN_DEFAULT_RISK)
INSERT INTO "MAE_CONTROL_IN_DEFAULT_RISK" ("N_CONTROL_ID_FK", "N_DEFAULT_RISK_ID_FK", "L_IS_ACTIVE", "N_COMPANY_ID_FK", "N_CREATION_USER_ID", "D_CREATION_DATE", "N_IS_DELETED")
SELECT l.control_id, nr."N_DEFAULT_RISK_ID_PK", true, 1, 1, now(), false
FROM (VALUES
    (1, 'Riesgo por contratación de personal sin verificación de antecedentes adecuada'),
    (2, 'Riesgo por ausencia de políticas de seguridad de la información aprobadas por la dirección'),
    (3, 'Riesgo por roles y responsabilidades de seguridad de la información no definidos'),
    (4, 'Riesgo por conflictos de interés o fraude por falta de segregación de funciones'),
    (5, 'Riesgo por responsabilidades de seguridad no gestionadas tras cambios organizacionales'),
    (6, 'Riesgo por incumplimiento de obligaciones de seguridad por falta de cláusulas contractuales claras'),
    (7, 'Riesgo por falta de coordinación oportuna con autoridades ante incidentes'),
    (8, 'Riesgo por desactualización frente a nuevas amenazas por falta de contacto con comunidades especializadas'),
    (9, 'Riesgo por explotación de amenazas emergentes no identificadas oportunamente'),
    (10, 'Riesgo por proyectos ejecutados sin considerar requisitos de seguridad de la información'),
    (11, 'Riesgo por activos de información no identificados ni inventariados'),
    (12, 'Riesgo por uso indebido de la información y otros activos asociados'),
    (13, 'Riesgo por fuga de información por activos no devueltos al finalizar la relación laboral o contractual'),
    (14, 'Riesgo por divulgación de información sensible por ausencia de clasificación'),
    (15, 'Riesgo por manejo inadecuado de información por falta de etiquetado'),
    (16, 'Riesgo por interceptación o pérdida de información durante su transferencia'),
    (17, 'Riesgo por acceso no autorizado a la información y los sistemas'),
    (18, 'Riesgo por suplantación de identidad por gestión deficiente de identidades digitales'),
    (19, 'Riesgo por compromiso de credenciales por gestión inadecuada de la información de autenticación'),
    (20, 'Riesgo por privilegios de acceso excesivos o no revisados periódicamente'),
    (21, 'Riesgo por brechas de seguridad originadas por proveedores'),
    (22, 'Riesgo por proveedores sin obligaciones contractuales de seguridad de la información'),
    (23, 'Riesgo por compromiso de la cadena de suministro de tecnología de la información'),
    (24, 'Riesgo por cambios no controlados en los servicios prestados por proveedores'),
    (25, 'Riesgo por uso inseguro de servicios en la nube'),
    (26, 'Riesgo por respuesta desorganizada o tardía ante incidentes de seguridad de la información'),
    (27, 'Riesgo por respuesta desorganizada o tardía ante incidentes de seguridad de la información'),
    (28, 'Riesgo por respuesta desorganizada o tardía ante incidentes de seguridad de la información'),
    (29, 'Riesgo por pérdida de aprendizaje organizacional y evidencia tras incidentes de seguridad'),
    (30, 'Riesgo por pérdida de aprendizaje organizacional y evidencia tras incidentes de seguridad'),
    (31, 'Riesgo por pérdida de continuidad de la seguridad de la información durante interrupciones'),
    (32, 'Riesgo por indisponibilidad de sistemas críticos por falta de preparación de continuidad TIC'),
    (33, 'Riesgo por incumplimiento de requisitos legales, reglamentarios o contractuales de seguridad'),
    (34, 'Riesgo por infracción de derechos de propiedad intelectual'),
    (35, 'Riesgo por pérdida, alteración o divulgación no autorizada de registros'),
    (36, 'Riesgo por incumplimiento de la normativa de protección de datos personales'),
    (37, 'Riesgo por deficiencias del SGSI no detectadas por falta de revisiones independientes'),
    (38, 'Riesgo por incumplimiento interno de las políticas y estándares de seguridad de la información'),
    (39, 'Riesgo por errores operativos por ausencia de procedimientos documentados'),
    (40, 'Riesgo por error humano por falta de concientización, educación y capacitación en seguridad'),
    (41, 'Riesgo por reincidencia de incumplimientos por ausencia de un proceso disciplinario formal'),
    (42, 'Riesgo por accesos o información retenida indebidamente tras la finalización del empleo'),
    (43, 'Riesgo por divulgación no autorizada de información por ausencia de acuerdos de confidencialidad'),
    (44, 'Riesgo por exposición de información en modalidades de trabajo remoto no seguras'),
    (45, 'Riesgo por eventos de seguridad no reportados oportunamente por el personal'),
    (46, 'Riesgo por acceso físico no autorizado a las instalaciones'),
    (47, 'Riesgo por ingreso no controlado de personas a áreas restringidas'),
    (48, 'Riesgo por exposición de información en oficinas, salas o instalaciones no aseguradas'),
    (49, 'Riesgo por incidentes físicos no detectados por falta de monitoreo'),
    (50, 'Riesgo por daño a instalaciones o equipos por amenazas físicas o ambientales'),
    (51, 'Riesgo por exposición de información en áreas seguras por controles de trabajo inadecuados'),
    (52, 'Riesgo por exposición de información por escritorios o pantallas desprotegidos'),
    (53, 'Riesgo por daño o pérdida de equipos por emplazamiento inadecuado'),
    (54, 'Riesgo por pérdida o robo de activos fuera de las instalaciones de la organización'),
    (55, 'Riesgo por interrupción de servicios por falla de utilidades de apoyo'),
    (56, 'Riesgo por fuga o pérdida de información por gestión inadecuada de medios de almacenamiento'),
    (57, 'Riesgo por interceptación o daño de datos por cableado no protegido'),
    (58, 'Riesgo por falla de equipos por mantenimiento insuficiente'),
    (59, 'Riesgo por fuga de información al eliminar o reutilizar equipos sin borrado seguro'),
    (60, 'Riesgo por compromiso de información en dispositivos de usuario final no protegidos'),
    (61, 'Riesgo por abuso de privilegios por gestión inadecuada de accesos privilegiados'),
    (62, 'Riesgo por acceso no autorizado a la información por restricciones de acceso insuficientes'),
    (63, 'Riesgo por manipulación no autorizada del código fuente'),
    (64, 'Riesgo por compromiso de cuentas por mecanismos de autenticación débiles'),
    (65, 'Riesgo por degradación o caída de servicios por capacidad de recursos insuficiente'),
    (66, 'Riesgo por infección de malware en los sistemas de información'),
    (67, 'Riesgo por explotación de vulnerabilidades técnicas no identificadas ni corregidas'),
    (68, 'Riesgo por configuraciones inseguras o no estandarizadas en los sistemas'),
    (69, 'Riesgo por recuperación no autorizada de información eliminada de forma insegura'),
    (70, 'Riesgo por exposición de datos sensibles en entornos no productivos'),
    (71, 'Riesgo por fuga de datos sensibles fuera de la organización'),
    (72, 'Riesgo por pérdida irrecuperable de información por ausencia o falla de copias de seguridad'),
    (73, 'Riesgo por interrupción del servicio por falta de redundancia en las instalaciones de procesamiento'),
    (74, 'Riesgo por actividad maliciosa no detectada por ausencia de registros (logs) de eventos'),
    (75, 'Riesgo por falta de monitoreo continuo de la actividad de los sistemas'),
    (76, 'Riesgo por trazabilidad de eventos comprometida por desincronización de relojes'),
    (77, 'Riesgo por uso indebido de herramientas de administración con privilegios elevados'),
    (78, 'Riesgo por instalación de software no autorizado o malicioso en los sistemas operativos'),
    (79, 'Riesgo por acceso no autorizado a la red por controles de red insuficientes'),
    (80, 'Riesgo por compromiso de servicios de red inseguros o mal configurados'),
    (81, 'Riesgo por propagación de incidentes entre segmentos de red por falta de segregación'),
    (82, 'Riesgo por acceso a contenido malicioso por ausencia de filtrado web'),
    (83, 'Riesgo por exposición de información sensible por ausencia o debilidad de controles criptográficos'),
    (84, 'Riesgo por vulnerabilidades introducidas por un ciclo de desarrollo de software inseguro'),
    (85, 'Riesgo por aplicaciones desarrolladas o adquiridas sin requisitos de seguridad definidos'),
    (86, 'Riesgo por diseño de sistemas sin principios de arquitectura de seguridad'),
    (87, 'Riesgo por explotación de vulnerabilidades por prácticas de codificación insegura'),
    (88, 'Riesgo por despliegue de software con vulnerabilidades no detectadas por falta de pruebas de seguridad'),
    (89, 'Riesgo por vulnerabilidades introducidas por desarrollo subcontratado sin supervisión de seguridad'),
    (90, 'Riesgo por contaminación de datos de producción por falta de separación entre entornos'),
    (91, 'Riesgo por incidentes causados por cambios no controlados en los sistemas'),
    (92, 'Riesgo por exposición de datos reales sensibles utilizados como información de prueba'),
    (93, 'Riesgo por interrupción o daño de sistemas de producción durante actividades de auditoría o pruebas')
) AS l(control_id, risk_name)
JOIN new_risks nr ON nr."C_NAME" = l.risk_name;

COMMIT;
