-- =====================================================================
-- Seed: una evidencia por requisito evaluado en 'Análisis de Brechas ISO 27001
-- - Junio 2026' (evaluationId=4)
-- Carga: MAE_DOCUMENTATION (9 nuevos documentos para temas sin catálogo
--        existente), MAE_REFERENCE_DOCUMENTATION (87 evidencias, una por
--        requirement_evaluation)
-- URL: se usa un patrón ficticio de intranet institucional
-- (https://intranet.onpe.gob.pe/...) en vez de un dominio real de internet,
-- ya que no corresponde inventar direcciones de terceros.
-- Requiere que ya existan las 87 filas en MAE_REQUIREMENT_EVALUATION para
-- evaluationId=4 (creadas por seed_requirement_evaluation_junio2026.sql).
-- Generado para revisión manual antes de ejecutar contra Railway/Postgres
-- =====================================================================

BEGIN;

-- 1) Documentos nuevos para temas sin entrada previa en MAE_DOCUMENTATION
WITH new_docs AS (
  INSERT INTO "MAE_DOCUMENTATION" ("C_NAME", "N_DOCUMENT_TYPE_ID", "N_STANDARD_ID", "N_COMPANY_ID", "N_CREATION_USER_ID", "D_CREATION_DATE", "N_IS_DELETED")
  VALUES
    ('Plan de Recursos del SGSI', 2, 4, 1, 1, now(), false),
    ('Plan de Objetivos de Seguridad de la Información', 1, 4, 1, 1, now(), false),
    ('Plan de Capacitación en Seguridad de la Información', 2, 4, 1, 1, now(), false),
    ('Programa de Concientización en Seguridad de la Información', 2, 4, 1, 1, now(), false),
    ('Procedimiento de Comunicación del SGSI', 2, 4, 1, 1, now(), false),
    ('Programa de Auditoría Interna del SGSI', 2, 4, 1, 1, now(), false),
    ('Tablero de Indicadores de Desempeño del SGSI', 2, 4, 1, 1, now(), false),
    ('Acta de Revisión por la Dirección', 3, 4, 1, 1, now(), false),
    ('Registro de Oportunidades de Mejora del SGSI', 2, 4, 1, 1, now(), false)
  RETURNING "N_DOCUMENTATION_ID_PK", "C_NAME"
),

-- 2) Lookup unificado: documentos nuevos + documentos ya existentes en el catálogo
doc_lookup AS (
  SELECT "N_DOCUMENTATION_ID_PK", "C_NAME" FROM new_docs
  UNION ALL
  SELECT "N_DOCUMENTATION_ID_PK", "C_NAME" FROM "MAE_DOCUMENTATION"
  WHERE "C_NAME" IN ('Análisis de contexto interno', 'Matriz de Partes Interesadas', 'Documento de Definición del Alcance del SGSI', 'Manual de Seguridad de la Información (DOC_SGSI_Manual_08.docx)', 'Política General del SGSI', 'Política General de Seguridad de la Información', 'Políticas Específicas del SGSI', 'Política de Roles y Responsabilidades del SGSI', 'Registro de riesgos y oportunidades identificados', 'Metodología de Evaluación de riesgos de seguridad de la información', 'Planes de acción para abordar riesgos y oportunidades', 'Modelo de Gestión documental del SGSI', 'Mapa de procesos', 'Documento de acciones correctivas y preventivas')
),

-- 3) Lookup de requirement_evaluation ya cargados para evaluationId=4
req_eval_lookup AS (
  SELECT "N_REQUIREMENT_EVALUATION_ID_PK", "N_REQUIREMENT_ID_FK" FROM "MAE_REQUIREMENT_EVALUATION" WHERE "N_EVALUATION_ID_FK"=4
)

-- 4) Una evidencia por requisito evaluado
INSERT INTO "MAE_REFERENCE_DOCUMENTATION" (
  "C_NAME", "C_DESCRIPTION", "N_DOCUMENTATION_ID_FK", "N_REQUIREMENT_EVALUATION_ID_FK",
  "N_EVALUATION_ID_FK", "N_COMPANY_ID_FK", "N_CREATION_USER_ID", "D_CREATION_DATE", "N_IS_DELETED", "C_URL"
)
SELECT l.evidence_name, l.evidence_desc, dl."N_DOCUMENTATION_ID_PK", rel."N_REQUIREMENT_EVALUATION_ID_PK",
       4, 1, 1, now(), false, l.evidence_url
FROM (VALUES
    (6, 'Análisis de contexto interno', 'Evidencia - Análisis de contexto interno', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Análisis de contexto interno.', 'https://intranet.onpe.gob.pe/sgsi/documentos/analisis-contexto-interno.pdf'),
    (7, 'Matriz de Partes Interesadas', 'Evidencia - Matriz de Partes Interesadas', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Matriz de Partes Interesadas.', 'https://intranet.onpe.gob.pe/sgsi/documentos/matriz-partes-interesadas.pdf'),
    (11, 'Documento de Definición del Alcance del SGSI', 'Evidencia - Documento de Definición del Alcance del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Documento de Definición del Alcance del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/definicion-alcance-sgsi.pdf'),
    (12, 'Política General del SGSI', 'Evidencia - Política General del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-sgsi.pdf'),
    (18, 'Manual de Seguridad de la Información (DOC_SGSI_Manual_08.docx)', 'Evidencia - Manual de Seguridad de la Información (DOC_SGSI_Manual_08.docx)', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Manual de Seguridad de la Información (DOC_SGSI_Manual_08.docx).', 'https://intranet.onpe.gob.pe/sgsi/documentos/manual-seguridad-informacion.pdf'),
    (19, 'Política General del SGSI', 'Evidencia - Política General del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-sgsi.pdf'),
    (20, 'Plan de Recursos del SGSI', 'Evidencia - Plan de Recursos del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Recursos del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-recursos-sgsi.pdf'),
    (21, 'Política General del SGSI', 'Evidencia - Política General del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-sgsi.pdf'),
    (22, 'Política General del SGSI', 'Evidencia - Política General del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-sgsi.pdf'),
    (23, 'Política General del SGSI', 'Evidencia - Política General del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-sgsi.pdf'),
    (24, 'Política General del SGSI', 'Evidencia - Política General del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-sgsi.pdf'),
    (25, 'Política General del SGSI', 'Evidencia - Política General del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-sgsi.pdf'),
    (27, 'Política General de Seguridad de la Información', 'Evidencia - Política General de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-seguridad-informacion.pdf'),
    (28, 'Política General de Seguridad de la Información', 'Evidencia - Política General de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-seguridad-informacion.pdf'),
    (29, 'Política General de Seguridad de la Información', 'Evidencia - Política General de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-seguridad-informacion.pdf'),
    (30, 'Política General de Seguridad de la Información', 'Evidencia - Política General de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política General de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-general-seguridad-informacion.pdf'),
    (31, 'Políticas Específicas del SGSI', 'Evidencia - Políticas Específicas del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Políticas Específicas del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politicas-especificas-sgsi.pdf'),
    (32, 'Políticas Específicas del SGSI', 'Evidencia - Políticas Específicas del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Políticas Específicas del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politicas-especificas-sgsi.pdf'),
    (33, 'Políticas Específicas del SGSI', 'Evidencia - Políticas Específicas del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Políticas Específicas del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politicas-especificas-sgsi.pdf'),
    (35, 'Política de Roles y Responsabilidades del SGSI', 'Evidencia - Política de Roles y Responsabilidades del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política de Roles y Responsabilidades del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-roles-responsabilidades-sgsi.pdf'),
    (36, 'Política de Roles y Responsabilidades del SGSI', 'Evidencia - Política de Roles y Responsabilidades del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Política de Roles y Responsabilidades del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/politica-roles-responsabilidades-sgsi.pdf'),
    (41, 'Metodología de Evaluación de riesgos de seguridad de la información', 'Evidencia - Metodología de Evaluación de riesgos de seguridad de la información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Metodología de Evaluación de riesgos de seguridad de la información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/metodologia-evaluacion-riesgos.pdf'),
    (42, 'Registro de riesgos y oportunidades identificados', 'Evidencia - Registro de riesgos y oportunidades identificados', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Registro de riesgos y oportunidades identificados.', 'https://intranet.onpe.gob.pe/sgsi/documentos/registro-riesgos-oportunidades.pdf'),
    (43, 'Registro de riesgos y oportunidades identificados', 'Evidencia - Registro de riesgos y oportunidades identificados', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Registro de riesgos y oportunidades identificados.', 'https://intranet.onpe.gob.pe/sgsi/documentos/registro-riesgos-oportunidades.pdf'),
    (47, 'Registro de riesgos y oportunidades identificados', 'Evidencia - Registro de riesgos y oportunidades identificados', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Registro de riesgos y oportunidades identificados.', 'https://intranet.onpe.gob.pe/sgsi/documentos/registro-riesgos-oportunidades.pdf'),
    (48, 'Registro de riesgos y oportunidades identificados', 'Evidencia - Registro de riesgos y oportunidades identificados', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Registro de riesgos y oportunidades identificados.', 'https://intranet.onpe.gob.pe/sgsi/documentos/registro-riesgos-oportunidades.pdf'),
    (49, 'Metodología de Evaluación de riesgos de seguridad de la información', 'Evidencia - Metodología de Evaluación de riesgos de seguridad de la información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Metodología de Evaluación de riesgos de seguridad de la información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/metodologia-evaluacion-riesgos.pdf'),
    (51, 'Planes de acción para abordar riesgos y oportunidades', 'Evidencia - Planes de acción para abordar riesgos y oportunidades', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Planes de acción para abordar riesgos y oportunidades.', 'https://intranet.onpe.gob.pe/sgsi/documentos/planes-accion-riesgos-oportunidades.pdf'),
    (52, 'Plan de Objetivos de Seguridad de la Información', 'Evidencia - Plan de Objetivos de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Objetivos de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-objetivos-seguridad-informacion.pdf'),
    (54, 'Plan de Objetivos de Seguridad de la Información', 'Evidencia - Plan de Objetivos de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Objetivos de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-objetivos-seguridad-informacion.pdf'),
    (55, 'Plan de Objetivos de Seguridad de la Información', 'Evidencia - Plan de Objetivos de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Objetivos de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-objetivos-seguridad-informacion.pdf'),
    (56, 'Plan de Objetivos de Seguridad de la Información', 'Evidencia - Plan de Objetivos de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Objetivos de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-objetivos-seguridad-informacion.pdf'),
    (57, 'Plan de Objetivos de Seguridad de la Información', 'Evidencia - Plan de Objetivos de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Objetivos de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-objetivos-seguridad-informacion.pdf'),
    (58, 'Plan de Objetivos de Seguridad de la Información', 'Evidencia - Plan de Objetivos de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Objetivos de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-objetivos-seguridad-informacion.pdf'),
    (59, 'Plan de Objetivos de Seguridad de la Información', 'Evidencia - Plan de Objetivos de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Objetivos de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-objetivos-seguridad-informacion.pdf'),
    (60, 'Plan de Objetivos de Seguridad de la Información', 'Evidencia - Plan de Objetivos de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Objetivos de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-objetivos-seguridad-informacion.pdf'),
    (61, 'Plan de Objetivos de Seguridad de la Información', 'Evidencia - Plan de Objetivos de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Objetivos de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-objetivos-seguridad-informacion.pdf'),
    (62, 'Plan de Objetivos de Seguridad de la Información', 'Evidencia - Plan de Objetivos de Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Objetivos de Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-objetivos-seguridad-informacion.pdf'),
    (68, 'Plan de Recursos del SGSI', 'Evidencia - Plan de Recursos del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Recursos del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-recursos-sgsi.pdf'),
    (69, 'Plan de Capacitación en Seguridad de la Información', 'Evidencia - Plan de Capacitación en Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Capacitación en Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-capacitacion-seguridad-informacion.pdf'),
    (70, 'Plan de Capacitación en Seguridad de la Información', 'Evidencia - Plan de Capacitación en Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Capacitación en Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-capacitacion-seguridad-informacion.pdf'),
    (71, 'Plan de Capacitación en Seguridad de la Información', 'Evidencia - Plan de Capacitación en Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Capacitación en Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-capacitacion-seguridad-informacion.pdf'),
    (72, 'Plan de Capacitación en Seguridad de la Información', 'Evidencia - Plan de Capacitación en Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Plan de Capacitación en Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/plan-capacitacion-seguridad-informacion.pdf'),
    (73, 'Programa de Concientización en Seguridad de la Información', 'Evidencia - Programa de Concientización en Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Programa de Concientización en Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/programa-concientizacion-seguridad-informacion.pdf'),
    (74, 'Programa de Concientización en Seguridad de la Información', 'Evidencia - Programa de Concientización en Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Programa de Concientización en Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/programa-concientizacion-seguridad-informacion.pdf'),
    (75, 'Programa de Concientización en Seguridad de la Información', 'Evidencia - Programa de Concientización en Seguridad de la Información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Programa de Concientización en Seguridad de la Información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/programa-concientizacion-seguridad-informacion.pdf'),
    (76, 'Procedimiento de Comunicación del SGSI', 'Evidencia - Procedimiento de Comunicación del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Procedimiento de Comunicación del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/procedimiento-comunicacion-sgsi.pdf'),
    (77, 'Modelo de Gestión documental del SGSI', 'Evidencia - Modelo de Gestión documental del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Modelo de Gestión documental del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/modelo-gestion-documental-sgsi.pdf'),
    (78, 'Modelo de Gestión documental del SGSI', 'Evidencia - Modelo de Gestión documental del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Modelo de Gestión documental del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/modelo-gestion-documental-sgsi.pdf'),
    (79, 'Modelo de Gestión documental del SGSI', 'Evidencia - Modelo de Gestión documental del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Modelo de Gestión documental del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/modelo-gestion-documental-sgsi.pdf'),
    (83, 'Mapa de procesos', 'Evidencia - Mapa de procesos', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Mapa de procesos.', 'https://intranet.onpe.gob.pe/sgsi/documentos/mapa-procesos.pdf'),
    (84, 'Modelo de Gestión documental del SGSI', 'Evidencia - Modelo de Gestión documental del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Modelo de Gestión documental del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/modelo-gestion-documental-sgsi.pdf'),
    (85, 'Mapa de procesos', 'Evidencia - Mapa de procesos', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Mapa de procesos.', 'https://intranet.onpe.gob.pe/sgsi/documentos/mapa-procesos.pdf'),
    (86, 'Mapa de procesos', 'Evidencia - Mapa de procesos', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Mapa de procesos.', 'https://intranet.onpe.gob.pe/sgsi/documentos/mapa-procesos.pdf'),
    (87, 'Metodología de Evaluación de riesgos de seguridad de la información', 'Evidencia - Metodología de Evaluación de riesgos de seguridad de la información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Metodología de Evaluación de riesgos de seguridad de la información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/metodologia-evaluacion-riesgos.pdf'),
    (88, 'Metodología de Evaluación de riesgos de seguridad de la información', 'Evidencia - Metodología de Evaluación de riesgos de seguridad de la información', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Metodología de Evaluación de riesgos de seguridad de la información.', 'https://intranet.onpe.gob.pe/sgsi/documentos/metodologia-evaluacion-riesgos.pdf'),
    (89, 'Planes de acción para abordar riesgos y oportunidades', 'Evidencia - Planes de acción para abordar riesgos y oportunidades', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Planes de acción para abordar riesgos y oportunidades.', 'https://intranet.onpe.gob.pe/sgsi/documentos/planes-accion-riesgos-oportunidades.pdf'),
    (90, 'Planes de acción para abordar riesgos y oportunidades', 'Evidencia - Planes de acción para abordar riesgos y oportunidades', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Planes de acción para abordar riesgos y oportunidades.', 'https://intranet.onpe.gob.pe/sgsi/documentos/planes-accion-riesgos-oportunidades.pdf'),
    (94, 'Tablero de Indicadores de Desempeño del SGSI', 'Evidencia - Tablero de Indicadores de Desempeño del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Tablero de Indicadores de Desempeño del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/tablero-indicadores-desempeno-sgsi.pdf'),
    (95, 'Tablero de Indicadores de Desempeño del SGSI', 'Evidencia - Tablero de Indicadores de Desempeño del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Tablero de Indicadores de Desempeño del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/tablero-indicadores-desempeno-sgsi.pdf'),
    (96, 'Tablero de Indicadores de Desempeño del SGSI', 'Evidencia - Tablero de Indicadores de Desempeño del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Tablero de Indicadores de Desempeño del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/tablero-indicadores-desempeno-sgsi.pdf'),
    (97, 'Tablero de Indicadores de Desempeño del SGSI', 'Evidencia - Tablero de Indicadores de Desempeño del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Tablero de Indicadores de Desempeño del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/tablero-indicadores-desempeno-sgsi.pdf'),
    (98, 'Tablero de Indicadores de Desempeño del SGSI', 'Evidencia - Tablero de Indicadores de Desempeño del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Tablero de Indicadores de Desempeño del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/tablero-indicadores-desempeno-sgsi.pdf'),
    (99, 'Tablero de Indicadores de Desempeño del SGSI', 'Evidencia - Tablero de Indicadores de Desempeño del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Tablero de Indicadores de Desempeño del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/tablero-indicadores-desempeno-sgsi.pdf'),
    (100, 'Programa de Auditoría Interna del SGSI', 'Evidencia - Programa de Auditoría Interna del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Programa de Auditoría Interna del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/programa-auditoria-interna-sgsi.pdf'),
    (101, 'Programa de Auditoría Interna del SGSI', 'Evidencia - Programa de Auditoría Interna del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Programa de Auditoría Interna del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/programa-auditoria-interna-sgsi.pdf'),
    (102, 'Programa de Auditoría Interna del SGSI', 'Evidencia - Programa de Auditoría Interna del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Programa de Auditoría Interna del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/programa-auditoria-interna-sgsi.pdf'),
    (103, 'Programa de Auditoría Interna del SGSI', 'Evidencia - Programa de Auditoría Interna del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Programa de Auditoría Interna del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/programa-auditoria-interna-sgsi.pdf'),
    (104, 'Programa de Auditoría Interna del SGSI', 'Evidencia - Programa de Auditoría Interna del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Programa de Auditoría Interna del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/programa-auditoria-interna-sgsi.pdf'),
    (105, 'Programa de Auditoría Interna del SGSI', 'Evidencia - Programa de Auditoría Interna del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Programa de Auditoría Interna del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/programa-auditoria-interna-sgsi.pdf'),
    (106, 'Programa de Auditoría Interna del SGSI', 'Evidencia - Programa de Auditoría Interna del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Programa de Auditoría Interna del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/programa-auditoria-interna-sgsi.pdf'),
    (107, 'Acta de Revisión por la Dirección', 'Evidencia - Acta de Revisión por la Dirección', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Acta de Revisión por la Dirección.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acta-revision-direccion.pdf'),
    (108, 'Acta de Revisión por la Dirección', 'Evidencia - Acta de Revisión por la Dirección', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Acta de Revisión por la Dirección.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acta-revision-direccion.pdf'),
    (109, 'Acta de Revisión por la Dirección', 'Evidencia - Acta de Revisión por la Dirección', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Acta de Revisión por la Dirección.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acta-revision-direccion.pdf'),
    (110, 'Acta de Revisión por la Dirección', 'Evidencia - Acta de Revisión por la Dirección', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Acta de Revisión por la Dirección.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acta-revision-direccion.pdf'),
    (111, 'Acta de Revisión por la Dirección', 'Evidencia - Acta de Revisión por la Dirección', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Acta de Revisión por la Dirección.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acta-revision-direccion.pdf'),
    (112, 'Acta de Revisión por la Dirección', 'Evidencia - Acta de Revisión por la Dirección', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Acta de Revisión por la Dirección.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acta-revision-direccion.pdf'),
    (115, 'Documento de acciones correctivas y preventivas', 'Evidencia - Documento de acciones correctivas y preventivas', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Documento de acciones correctivas y preventivas.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acciones-correctivas-preventivas.pdf'),
    (116, 'Documento de acciones correctivas y preventivas', 'Evidencia - Documento de acciones correctivas y preventivas', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Documento de acciones correctivas y preventivas.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acciones-correctivas-preventivas.pdf'),
    (117, 'Documento de acciones correctivas y preventivas', 'Evidencia - Documento de acciones correctivas y preventivas', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Documento de acciones correctivas y preventivas.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acciones-correctivas-preventivas.pdf'),
    (119, 'Documento de acciones correctivas y preventivas', 'Evidencia - Documento de acciones correctivas y preventivas', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Documento de acciones correctivas y preventivas.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acciones-correctivas-preventivas.pdf'),
    (120, 'Documento de acciones correctivas y preventivas', 'Evidencia - Documento de acciones correctivas y preventivas', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Documento de acciones correctivas y preventivas.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acciones-correctivas-preventivas.pdf'),
    (121, 'Documento de acciones correctivas y preventivas', 'Evidencia - Documento de acciones correctivas y preventivas', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Documento de acciones correctivas y preventivas.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acciones-correctivas-preventivas.pdf'),
    (122, 'Documento de acciones correctivas y preventivas', 'Evidencia - Documento de acciones correctivas y preventivas', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Documento de acciones correctivas y preventivas.', 'https://intranet.onpe.gob.pe/sgsi/documentos/acciones-correctivas-preventivas.pdf'),
    (123, 'Registro de Oportunidades de Mejora del SGSI', 'Evidencia - Registro de Oportunidades de Mejora del SGSI', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Registro de Oportunidades de Mejora del SGSI.', 'https://intranet.onpe.gob.pe/sgsi/documentos/registro-oportunidades-mejora-sgsi.pdf'),
    (127, 'Matriz de Partes Interesadas', 'Evidencia - Matriz de Partes Interesadas', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Matriz de Partes Interesadas.', 'https://intranet.onpe.gob.pe/sgsi/documentos/matriz-partes-interesadas.pdf'),
    (128, 'Matriz de Partes Interesadas', 'Evidencia - Matriz de Partes Interesadas', 'Evidencia documental que sustenta la evaluación del requisito, referida a: Matriz de Partes Interesadas.', 'https://intranet.onpe.gob.pe/sgsi/documentos/matriz-partes-interesadas.pdf')
) AS l(requirement_id, doc_name, evidence_name, evidence_desc, evidence_url)
JOIN doc_lookup dl ON dl."C_NAME" = l.doc_name
JOIN req_eval_lookup rel ON rel."N_REQUIREMENT_ID_FK" = l.requirement_id;

COMMIT;
