-- =====================================================================
-- Seed: una brecha (MAE_BREACH) por cada requisito 'NO CUMPLIDO' en la
-- evaluación 'Análisis de Brechas ISO 27001 - Junio 2026' (evaluationId=4)
-- Alcance: los 14 requisitos con calificación IN (Inicial) o NI (No
--          implementado), que coinciden exactamente con el conteo
--          "NO CUMPLIDOS (14)" mostrado en la UI para esta evaluación.
-- Todas de tipo Requerimiento (C_TYPE=1), estado inicial "Abierta".
-- Generado para revisión manual antes de ejecutar contra Railway/Postgres
-- =====================================================================

BEGIN;

INSERT INTO "MAE_BREACH" (
  "N_EVALUATION_ID_FK", "N_STANDARD_ID_FK", "C_TYPE", "N_REQUIREMENT_ID_FK", "N_CONTROL_ID_FK",
  "C_TITLE", "C_DESCRIPTION", "N_BREACH_SEVERITY_ID_FK", "N_BREACH_STATUS_ID_FK", "N_RESPONSIBLE_ID_FK",
  "C_EVIDENCE_DESCRIPTION", "N_COMPANY_ID_FK", "N_CREATION_USER_ID", "D_CREATION_DATE", "N_IS_DELETED", "C_NUMERATION_TO_SHOW"
)
VALUES
  (4, 4, '1', 7, 0, 'El requisito 4.2.1 no se cumple: Las partes interesadas pertinentes al sistema de gestión de seguridad de la información', 'No se ha formalizado un registro de partes interesadas del SGSI (entes reguladores, ciudadanía, proveedores TI, otras entidades del Estado). Solo existe una identificación inicial sin análisis sistemático.', 3, 1, 9, 'No existe un documento formal de identificación de partes interesadas; solo notas preliminares dispersas.', 1, 1, now(), false, '4.2.1'),
  (4, 4, '1', 127, 0, 'El requisito 4.2.2 no se cumple: Los requisitos pertinentes de estas partes interesadas', 'Al no existir un registro formal de partes interesadas, tampoco se han determinado ni documentado sus requisitos pertinentes de forma sistemática.', 3, 1, 9, 'No se encontró una matriz de requisitos de partes interesadas vinculada al SGSI.', 1, 1, now(), false, '4.2.2'),
  (4, 4, '1', 128, 0, 'El requisito 4.2.3 no se cumple: Cuáles de estos requisitos se abordarán mediante el sistema de gestión de seguridad de la información.', 'No se ha determinado qué requisitos de partes interesadas serán abordados por el SGSI, al faltar el insumo previo (registro y análisis de requisitos).', 3, 1, 9, 'No existe documento que vincule requisitos de partes interesadas con el alcance del SGSI.', 1, 1, now(), false, '4.2.3'),
  (4, 4, '1', 52, 0, 'El requisito 6.2.1 no se cumple: Asegurar la consistencia de los objetivos y la planificación con las políticas de seguridad de la información', 'Los objetivos de seguridad de la información definidos no cuentan con una vinculación formal y documentada con la política de seguridad ni con el contexto de riesgo evaluado.', 2, 1, 12, 'El plan de objetivos vigente no referencia explícitamente la política de seguridad ni la evaluación de riesgos.', 1, 1, now(), false, '6.2.1'),
  (4, 4, '1', 54, 0, 'El requisito 6.2.2 no se cumple: Realizar  la medición de los objetivos en cuanto a su consecución', 'No se ha implementado un mecanismo de medición del cumplimiento de los objetivos de seguridad de la información planteados.', 2, 1, 12, 'No existen indicadores ni reportes de seguimiento de cumplimiento de objetivos.', 1, 1, now(), false, '6.2.2'),
  (4, 4, '1', 55, 0, 'El requisito 6.2.3 no se cumple: Tomar en cuenta los requisitos aplicables de seguridad de la información, resultados de la valoración y tratamiento de riesgos para formular los objetivos y la planificación ', 'La formulación de los objetivos de seguridad no incorpora de manera documentada los resultados de la evaluación y tratamiento de riesgos vigente.', 2, 1, 12, 'El plan de objetivos no cita ni referencia el registro de riesgos evaluados.', 1, 1, now(), false, '6.2.3'),
  (4, 4, '1', 56, 0, 'El requisito 6.2.4 no se cumple: Comunicar a las partes pertinentes en la organización los objetivos y la planificación ', 'Los objetivos de seguridad de la información y su planificación no han sido comunicados formalmente a las partes pertinentes dentro de la organización.', 2, 1, 12, 'No hay evidencia de comunicados, correos o actas donde se difundan los objetivos de seguridad.', 1, 1, now(), false, '6.2.4'),
  (4, 4, '1', 57, 0, 'El requisito 6.2.5 no se cumple: Actualizar y mantener documentado según sea apropiado', 'Los objetivos de seguridad de la información no cuentan con un procedimiento de actualización periódica ni versión documentada vigente.', 2, 1, 12, 'El documento de objetivos disponible no tiene control de versiones ni fecha de última actualización.', 1, 1, now(), false, '6.2.5'),
  (4, 4, '1', 58, 0, 'El requisito 6.2.6 no se cumple: La planificación debe prever las actividades necesarias para lograr los objetivos', 'No existe una planificación formal que detalle las actividades necesarias para el logro de cada objetivo de seguridad de la información definido.', 3, 1, 12, 'No se encontró un plan de actividades asociado a los objetivos de seguridad.', 1, 1, now(), false, '6.2.6'),
  (4, 4, '1', 59, 0, 'El requisito 6.2.7 no se cumple: La planificación debe prever los recursos que serán requeridos para lograr los objetivos', 'La planificación de objetivos de seguridad no identifica ni asigna los recursos (presupuesto, personal, herramientas) necesarios para su cumplimiento.', 3, 1, 12, 'No existe un presupuesto o asignación de recursos vinculada a los objetivos de seguridad.', 1, 1, now(), false, '6.2.7'),
  (4, 4, '1', 60, 0, 'El requisito 6.2.8 no se cumple: La planificación debe prever la asignación de responsabilidades para su ejecución', 'No se han asignado responsables formales para la ejecución de las actividades que permitirían el cumplimiento de los objetivos de seguridad.', 3, 1, 12, 'El plan de objetivos no contiene una columna o registro de responsables por actividad.', 1, 1, now(), false, '6.2.8'),
  (4, 4, '1', 61, 0, 'El requisito 6.2.9 no se cumple: La planificación y los objetivos deben prever plazos para su culminación', 'La planificación de objetivos de seguridad no establece plazos ni fechas límite para la culminación de las actividades asociadas.', 3, 1, 12, 'No se encontró un cronograma con fechas de cumplimiento para los objetivos de seguridad.', 1, 1, now(), false, '6.2.9'),
  (4, 4, '1', 62, 0, 'El requisito 6.2.10 no se cumple: La planificación debe prever cómo se evaluarán los resultado', 'No se ha definido un método o criterio para evaluar los resultados obtenidos respecto a los objetivos de seguridad de la información planificados.', 3, 1, 12, 'No existe un procedimiento o criterio documentado de evaluación de resultados de los objetivos.', 1, 1, now(), false, '6.2.10'),
  (4, 4, '1', 76, 0, 'El requisito 7.4.1 no se cumple: Determinar la necesidad de la comunicación interna y externa relevante al SGSI, incluyendo el qué, cuándo, a quién, quién y procesos para la comunicación ', 'No existe un procedimiento formal que determine qué, cuándo, a quién, quién y cómo comunicar interna y externamente asuntos relevantes del SGSI; solo se realizan comunicaciones puntuales.', 2, 1, 1, 'No se encontró un procedimiento de comunicación del SGSI ni un registro de comunicaciones realizadas.', 1, 1, now(), false, '7.4.1');

COMMIT;
